// Copyright (c) Ubisoft. All Rights Reserved.
// Licensed under the Apache 2.0 License. See LICENSE.md in the project root for license information.

// ═════════════════════════════════════════════════════════════════════════════
// STAGE plugin_loadlibrary — Plugin DLL: GreeterDomain capability registration
// ─────────────────────────────────────────────────────────────────────────────
// This file compiles into a shared library (.dll / .so).  It declares the
// same domain/model/contract types as the host (in a real project these would
// live in a shared header), registers capabilities, and exposes the two C ABI
// entry points (CRG_Bootstrap / CRG_Shutdown) via CRG_DEFINE_PLUGIN.
//
// No GridZero .cpp is compiled here — only headers from crg_core (header-only).
// The host calls CRG_Bootstrap once after dlopen, then CRG_Shutdown before
// dlclose; both are generated by the macro.
// ═════════════════════════════════════════════════════════════════════════════

#include "crg/plugin/plugin.hpp"
#include "crg/crg.hpp"
#include "crg/capabilities/capability_binding.hpp"

// ─── Shared domain/model/contract (mirror of host declarations) ───────────────
struct GreeterDomain {};
CRG_DECLARE_DOMAIN(GreeterDomain)

struct IGreet {
    struct Params { const char* m_Out{ nullptr }; };
};
CRG_DECLARE_CONTRACT(IGreet)

template<> struct crg::routing::CapabilityRoutingTraits<GreeterDomain, IGreet> {
    using SpaceType = crg::routing::CapabilitySpace<>;
};

struct English {};
struct French  {};

CRG_DECLARE_DOMAIN_MODELS(GreeterDomain,
    English,
    French)

// ─── Capabilities ─────────────────────────────────────────────────────────────
template<typename TModel>
struct EnglishGreet : crg::capabilities::Capability<IGreet> {
    static void Execute(IGreet::Params& p) { p.m_Out = "Hello from plugin"; }
};

template<typename TModel>
struct FrenchGreet : crg::capabilities::Capability<IGreet> {
    static void Execute(IGreet::Params& p) { p.m_Out = "Bonjour du plugin"; }
};

// ─── Bindings ─────────────────────────────────────────────────────────────────
namespace {
    static const crg::capabilities::CapabilityBinding<GreeterDomain, English, EnglishGreet> s_en;
    static const crg::capabilities::CapabilityBinding<GreeterDomain, French,  FrenchGreet>  s_fr;
}

// ─── Plugin entry points ──────────────────────────────────────────────────────
CRG_DEFINE_PLUGIN(Greeter)
CRG_DEFINE_DOMAIN(GreeterDomain)
