// Copyright (c) Ubisoft. All Rights Reserved.
// Licensed under the Apache 2.0 License. See LICENSE.md in the project root for license information.

// ═════════════════════════════════════════════════════════════════════════════
// STAGE plugin_loadlibrary — Manual-Load Plugin: the CppCon Acte 1 pattern
// ─────────────────────────────────────────────────────────────────────────────
// PROBLEM:
//   You want to load a plugin .dll/.so at runtime, have it inject capabilities
//   into the host routing tensor, invoke them, and cleanly unload — without any
//   managed loader, without any GridZero .cpp compiled into the host or plugin,
//   and without any code change on the host side.
//
// SOLUTION — Manual LoadLibrary + CRG_Bootstrap / CRG_Shutdown:
//   1. The HOST builds a HostDescriptor (its AnchorLink chain head) and a
//      CRG_Context pointing to it.
//   2. The HOST calls LoadLibrary / dlopen (its own code — zero GridZero .cpp).
//   3. The HOST looks up CRG_Bootstrap and calls it with the context.
//      CRG_Bootstrap (generated by CRG_DEFINE_PLUGIN in the DLL) splices the
//      plugin's local AnchorLink chain into the host anchor, then calls each
//      ISyncNode::OnPluginLoad — all via the header-only machinery in crg_core.
//   4. The HOST refreshes the routing cache (CapabilityRouter::RefreshCache)
//      so the new capabilities become visible to Find().
//   5. The HOST invokes capabilities as usual — the plugin's Execute() runs.
//   6. The HOST calls CRG_Shutdown, then dlclose/FreeLibrary.
//      CRG_Shutdown splices the plugin's chain back out; RefreshCache restores
//      the pre-load state.
//
// WHAT THIS STAGE PROVES:
//   - Zero GridZero .cpp in the host binary.
//   - Zero GridZero .cpp in the plugin binary (only headers from crg_core).
//   - The host writes one LoadLibrary + two GetProcAddress calls; that is the
//     entire integration surface.
//   - After unload, the routing tensor is identical to the pre-load state.
//
// DEPENDENCIES:
//   - crg_core (header-only)
//   - CRG_PLUGINS_ENABLED=1 (activates plugin.hpp / universal_anchor / ISyncNode)
//   - CRG_GREETER_PLUGIN_PATH injected by CMake (path to the built DLL/SO)
// ═════════════════════════════════════════════════════════════════════════════

#include "catch.hpp"
#include "crg/crg.hpp"
#include "crg/plugin/plugin.hpp"
#include "crg/host/host_descriptor.hpp"

// ─── OS dynamic-library helpers ───────────────────────────────────────────────
#if defined(_WIN32)
#  define WIN32_LEAN_AND_MEAN
#  include <windows.h>
using DylibHandle = HMODULE;
static DylibHandle  OpenDylib(const char* p) { return ::LoadLibraryA(p); }
static void*        GetSym(DylibHandle h, const char* n) { return reinterpret_cast<void*>(::GetProcAddress(h, n)); }
static void         CloseDylib(DylibHandle h) { ::FreeLibrary(h); }
#else
#  include <dlfcn.h>
using DylibHandle = void*;
static DylibHandle  OpenDylib(const char* p) { return ::dlopen(p, RTLD_NOW | RTLD_LOCAL); }
static void*        GetSym(DylibHandle h, const char* n) { return ::dlsym(h, n); }
static void         CloseDylib(DylibHandle h) { ::dlclose(h); }
#endif

// ─── Shared domain/model/contract (same declarations as plugin_greeter.cpp) ──
//   In a real project these live in a header shared between host and plugin.
struct GreeterDomain {};
CRG_DECLARE_DOMAIN(GreeterDomain)
CRG_DEFINE_DOMAIN(GreeterDomain)

struct IGreet {
    struct Params { const char* m_Out{ nullptr }; };
};

template<> struct crg::routing::CapabilityRoutingTraits<GreeterDomain, IGreet> {
    using SpaceType = crg::routing::CapabilitySpace<>;
};

struct English {};
struct French  {};

CRG_DECLARE_DOMAIN_MODELS(GreeterDomain,
    English,
    French)

// CRG_IMPLEMENT_PARTITION anchors the DenseIndexStore for this domain in
// this TU — required exactly once per domain per binary (host side).
CRG_IMPLEMENT_PARTITION(GreeterDomain)

// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("Stage plugin_loadlibrary — manual LoadLibrary splices plugin capabilities", "[plugin_loadlibrary]") {
    using namespace crg;
    using namespace crg::models;
    using namespace crg::routing;
    using namespace crg::capabilities;
    using namespace crg::discovery;

    // 1. Before load: no capability binding — Find returns an empty token.
    {
        auto token = ModelToken<GreeterDomain>::FromType<English>();
        auto gate  = CapabilityRouter<GreeterDomain>::Find<IGreet>(token);
        REQUIRE(!gate);
    }

    // 2. Build the host context (AnchorLink chain head from this process).
    ::crg::host::HostDescriptor hostDesc;
    hostDesc.m_HostAnchorsHead = ::crg::discovery::AnchorLink::GetLocalHead();

    ::crg::host::CRG_Context ctx{};
    ctx.m_HostDescriptor = &hostDesc;

    // 3. Load the plugin DLL (user's own LoadLibrary — zero GridZero .cpp).
#ifndef CRG_GREETER_PLUGIN_PATH
    FAIL("CRG_GREETER_PLUGIN_PATH not defined — CMake must inject this macro");
#endif
    DylibHandle dylib = OpenDylib(CRG_GREETER_PLUGIN_PATH);
    REQUIRE(dylib != nullptr);

    // 4. Resolve and call CRG_Bootstrap — splices plugin chain into host anchors.
    auto bootstrap = reinterpret_cast<crg::plugin::PluginLoader::BootstrapFn>(
        GetSym(dylib, crg::plugin::PluginSymbols::Bootstrap));
    REQUIRE(bootstrap != nullptr);
    bootstrap(&ctx);

    // 5. Refresh so CapabilityRouter sees the newly spliced populators.
    CapabilityRouter<GreeterDomain>::RefreshCache();

    // 6. Invoke — plugin's Execute() runs, no virtual call on the Muscle path.
    {
        auto token = ModelToken<GreeterDomain>::FromType<English>();
        auto gate  = CapabilityRouter<GreeterDomain>::Find<IGreet>(token);
        REQUIRE(gate);
        IGreet::Params p{};
        gate(p);
        REQUIRE(p.m_Out != nullptr);
        REQUIRE(std::string_view(p.m_Out) == "Hello from plugin");
    }
    {
        auto token = ModelToken<GreeterDomain>::FromType<French>();
        auto gate  = CapabilityRouter<GreeterDomain>::Find<IGreet>(token);
        REQUIRE(gate);
        IGreet::Params p{};
        gate(p);
        REQUIRE(p.m_Out != nullptr);
        REQUIRE(std::string_view(p.m_Out) == "Bonjour du plugin");
    }

    // 7. Shutdown + close — plugin chain spliced back out.
    auto shutdown = reinterpret_cast<crg::plugin::PluginLoader::ShutdownFn>(
        GetSym(dylib, crg::plugin::PluginSymbols::Shutdown));
    REQUIRE(shutdown != nullptr);
    shutdown();
    CloseDylib(dylib);

    // 8. Refresh again — routing tensor returns to pre-load state.
    CapabilityRouter<GreeterDomain>::RefreshCache();

    {
        auto token = ModelToken<GreeterDomain>::FromType<English>();
        auto gate  = CapabilityRouter<GreeterDomain>::Find<IGreet>(token);
        REQUIRE(!gate);
    }
}
